### ISSUE TITLE
Testing Data

### ISSUE THREAD

**Issue by rustagiadi95** [jhyuklee/ethnicity-tensorflow#1]
Hello There, I just read your paper, it is very informative and helpful. I just want to know that why the data_ijcai_author has been used as the testing dataset and not the file data_raw_test?

As the system is not able to read the data_ijcai_author for some reason unknown, so i wanted to ask if we can use the data_raw_test file as its replacement?

Thanks in advance

**Comment by jhyuklee** [comment]
Hi @rustagiadi95 ,
you can use both raw and cleaned versions of the paper.
You can just ignore the data_ijcai_author file.

**Comment by rustagiadi95** [comment]
Hi, thanks for the reply, although my question was different, I am not asking about the clean or raw data.I currently want to work on the raw data folder. I am asking about the file that can be used as the testing file......The file you currently used is the ijcai file for testing....I am asking that, can I use the data_raw_test in place of that for testing?

**Comment by jhyuklee** [comment]
Yes, you can. I'm not sure why you are mentioning ijcai file, because it was only used for internal use. You can change the argument in main.py to whatever you like.

**Comment by rustagiadi95** [comment]
Got it. Thanks a lot.
