### ISSUE TITLE
Output of the LSTMs

### ISSUE THREAD

**Issue by rustagiadi95** [jhyuklee/ethnicity-tensorflow#2]
Hi there, thanks for being so helpful with my last issue.
The one I am having right now that, I don't know tensorflow yet. I am working my way through your code.

1) Its a silly question from my side, but still I would like to know that whenever you are passing n-grams to the corresponding LSTM model, then are you collecting the ouputs of all the time steps to forward em to the linear layer or only the last output of the LSTM for that?

2) The padding that you have done for making the LSTM outputs of same size for all the data points via tf.gather(which has a very interesting and a particular way of padding the input based on the max_time_step), does it needs to be padded that way only or you can we pad it in other ways as well?

**Comment by jhyuklee** [comment]
Hi @rustagiadi95,

1=> only the last output of LSTM is passed.
2=> you can pad them any way you want, but we recommend using the default code.

Thanks.
